### ISSUE TITLE
Add originalyear support to MPC status

### ISSUE THREAD

**Issue by chowbok** [MusicPlayerDaemon/mpc#1]
Now that MPD supports the "originaldate" field, can we have MPC support it so we can do mpc -f "%originaldate%"?

**Comment by MaxKellermann** [comment]
All new core tags are automatically supported by mpc (and ncmpc); all you need is a libmpdclient version which supports the tag. libmpdclient 2.12 will support it, which is not yet released - but you can use git master until that happens.
