### ISSUE TITLE
mpc dont returns any output

### ISSUE THREAD

**Issue by l7ssha** [MusicPlayerDaemon/mpc#10]
Hello, I have lemonbar starting with openbox session, however command `mpc current` never returns value, even if I have refreshing rate at 5s and music is playing.

[Gist with my configuration](https://gist.github.com/l7ssha/319ad702e7929fb8ac73f713a12c6795) 

EDIT: If I start it from command line it works just fine..
EDIT2: Arch Linux, latest kernel

**Comment by MaxKellermann** [comment]
This bug report is completely devoid of information, I don't even know your mpc version number. And since mpc works well for you, there must be something wrong with your openbox session. But I don't know because I have no information.
