### ISSUE TITLE
mpc current -f "%artist%" returns blank

### ISSUE THREAD

**Issue by bonelifer** [MusicPlayerDaemon/mpc#100]
In both MPD: 0.23.12 or git master(0.24) 

Using this script: https://gist.github.com/jesvs/bd0d00e736503fb3385f799dad1aeaac
Also happens on terminal: 
mpc current -f "%artist%"

Using playerctl works
playerctl metadata artist

So mpd is outputting the artist tag. I tried it on other tags and they were also blank.

**Comment by bonelifer** [comment]
Synaptic says it's mpc .34-1
Xubuntu 22.04
Not sure what you mean.

**Comment by MaxKellermann** [comment]
Capture the MPD protocol between MPC and mpc.

**Comment by bonelifer** [comment]
how would I do that?

**Comment by MaxKellermann** [comment]
strace, wireshark, tcpdump - there are many tools for the job.

**Comment by MaxKellermann** [comment]
No reply
