### ISSUE TITLE
Audio format in the --format options?

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/mpc#101]
mpc can find songs based on AudioFormat e.g. `AudioFormat==192000:24:2` but when I want to understand what is the audio format per a given say song `mpc current` for example...there is no way to see it (unlike the mpd clients which provide it)

Can this be added?

**Comment by MaxKellermann** [comment]
I don't understand what you want. You "want to understand what is the audio format per a given say song ..." and this is where my brain is already unable to parse the sentence.

**Comment by roizcorp** [comment]
Sorry, I will try to rephrase

As a user I want to  punch `mpc current -f "%audioformat%"` - so mpc will show me the audio properties of the (current) song

**Comment by roizcorp** [comment]
thank you very much!
