### ISSUE TITLE
Can't save queue to a playlist with dash (minus) at the beginning of the playlist name

### ISSUE THREAD

**Issue by Schlaefer** [MusicPlayerDaemon/mpc#104]
# Steps to reproduce

Try to save the current queue to a new playlist providing a playlist name starting with *-*

`mpc --host=<host> save "- test"`

# Observed result

```
mpc: invalid option - test
```

No playlist is created

# Expected result

The mpd instance should create a new playlist with the name *- test*

# Environment

mpc version 0.34
mpd version 0.23.12

**Comment by Delapouite** [comment]
Hi.
I don't have `mpc` on my current machine to test it right now. Usually in CLI tools needing this kind of disambiguation between flags and other arguments, you can use `--`. So it *may* works:

```sh
mpc --host=<host> save -- "- test"
```

**Comment by MaxKellermann** [comment]
Thanks @Delapouite, that's exactly how it works - mpc follows the GNU convention here. But this fact isn't documented in the manpage, so this is a bug, though only a documentation bug.

**Comment by Schlaefer** [comment]
Thanks, that works (same with `rm` for removing). - Leave the ticket open as "documentation reminder" or close?

**Comment by MaxKellermann** [comment]
Leave open.
