### ISSUE TITLE
FR: Station name in status

### ISSUE THREAD

**Issue by gerroon** [MusicPlayerDaemon/mpc#13]
Hi

I really like Mpc, it works great. It shows the current playing song from a station when streaming but it would be much nicer if there is a way to also provide the station url and the name when mpc status is fried if an internet stream is playing on the Mpd instance.

thanks

**Comment by MaxKellermann** [comment]
RTFM on the `-f` option.

**Comment by gerroon** [comment]
Thanks for the treply CDFB YAPA 

cheers
