### ISSUE TITLE
Add ability to set the rating

### ISSUE THREAD

**Issue by internethering** [MusicPlayerDaemon/mpc#15]
Hi,

I own a Korg Nanocontrol, which is perfect to control mpd (play, pause, next, ...). A litte bash script, aseqdump & mpc: https://paste.pound-python.org/show/TwdNe94LUzo4TejR0Dlc/
I would like to set the rating by the Nanocontrol too, may you add the ability to mpc? like: '`mpc rate [<0-5>]`'

Greetings
Richard

**Comment by MaxKellermann** [comment]
And what command is mpc supposed to send to MPD?

**Comment by internethering** [comment]
https://www.musicpd.org/doc/protocol/ says:

> The Sticker Database
> 
> "Stickers" are pieces of information attached to songs. Some clients use them to store ratings and other volatile data. 

I grepped the sourcecode of cantata, the file mpd-interface/mpdconnection.cpp provides functions like setRating(): "`cmd+="sticker set song "+encodeName(f)+' '+constRatingSticker+' '+quote(val)+'\n';`" and getRating(): "`Response resp=sendCommand("sticker get song "+encodeName(file)+' '+constRatingSticker, false);`

see also https://www.musicpd.org/doc/protocol/stickers.html

**Comment by MaxKellermann** [comment]
mpc already has the ability to set stickers since version 0.19, released in 2009.

**Comment by internethering** [comment]
nice. It isn't documented in the man page, so I asked her. For the protocol, to set 5-star rating, the command is:

`mpc sticker "`mpc -f %file% current`" set rating 10`
