### ISSUE TITLE
Add ability for "negative" searches

### ISSUE THREAD

**Issue by chowbok** [MusicPlayerDaemon/mpc#2]
It'd be nice to have the ability to do "not"-searches, like get a list of tracks that aren't a particular genre.

**Comment by MaxKellermann** [comment]
This is not supported by MPD - please open the same ticket on MPD, and when that one is done, we can support it in mpc.

**Comment by millette** [comment]
Depends on [mpd/89](https://github.com/MusicPlayerDaemon/MPD/issues/89)

**Comment by roizcorp** [comment]
+1

**Comment by roizcorp** [comment]
so I see MPD has implemented negative condition https://www.musicpd.org/doc/protocol/filter_syntax.html 
I tried this in mpc 0.30 and it didn't recognize it, also MPD added "modified-since" and I failed to use it in mpc

**Comment by roizcorp** [comment]
I'm sorry Max, it simply does not work, I updated all the packages (0.21 and 0.31) and databases (after mpd 0.21  upgrade my database was lost)

`mpc search (AlbumArtist=="Yanni")
-bash: syntax error near unexpected token `('`

**Comment by millette** [comment]
@roizcorp Can you try

```sh
mpc search albumartist yanni
```

Not sure where you say that syntax, but bash requires () to be quoted, although they're not needed at all here.

**Comment by MaxKellermann** [comment]
@milette is right, @roizcorp failed at basic `bash` syntax, and this mistake has nothing to do with MPD or mpc. This is how to properly quote the parameter for `bash`:
`mpc search '(AlbumArtist=="Yanni")'`
But since this is about negative serarches, one could do:
`mpc search '(AlbumArtist!="Yanni")'`

**Comment by roizcorp** [comment]
Thank you guys, as you nicely phrased I "failed at basic bash syntax". I would kindly suggest to fix to documentaion as it is MISLEADING basic bash or not...
I put the link above but here it again https://www.musicpd.org/doc/protocol/filter_syntax.html 

And here is the quote-  find "(artist \"foo\\'bar\\\"\")"

So forgive me for the trouble ! And please fix the doc

**Comment by millette** [comment]
@roizcorp There are many encoding levels. The docs you point to deal with the TCP protocol between mpd and mpc, with its own escape rules. Bash is another level. Hope that helps. If you need more help, try the [forum](https://forum.musicpd.org/viewforum.php?f=12).
