### ISSUE TITLE
enhancement: "mpc seek" beyond limits of a track

### ISSUE THREAD

**Issue by jborme** [MusicPlayerDaemon/mpc#21]
It would be nice if seek would understand track limits and seek through the playlist until the desired time (forward or backward) is reached. Right now, seek only works within a track, and if the user asks to seek a too large offset, nothing happens (or glitches). At least, skipping to next or previous would make sense.

As a user, I interact with my music with keyboard shortcuts for "mpc seek +0:00:30", -30 s, or +-5 min. I would like to be able to skip forward 5 min within an album even if it is split into shorter tracks, and I would like to be able to skip backwards 30 s to listen again to the end of the previous track.

**Comment by jborme** [comment]
Attached a patch that implements the feature. I can make a pull request if the maintainer has interest in the feature.

Description:
The seek function will be able to seek through successive tracks if the seek
duration does not fit within a track, calling next/previous and updating the 
remaining duration accordingly.

If seeking forward through the end of the playlist, it will let the playlist
finish.

If seeking backwards through the beginning, will position at the beginning of
the playlist. It does not know where it is in the playlist, it will just call
previous enough times to seek backwards by the indicated amount using the
track duration as duration iteration, possibly calling previous unnecessarily 
if already at the first track of the playlis.

There is an arbitrary limit of 100 next/previous iterations to avoid infinite
loops (could happen if seeking backwards through the beginning and the first
track has a duration of 0 second).

Respects the pause/playing state of the player.

[seek_through_patch.txt](https://github.com/MusicPlayerDaemon/mpc/files/1958965/seek_through_patch.txt)

**Comment by MaxKellermann** [comment]
That may be an interesting feature, but it should be optional. Make this a PR and we can discuss what else is wrong with your patch to get it merged eventually.

**Comment by jborme** [comment]
Since you asked to make it optional, the implementation made it a new command. Pull request #22

**Comment by MaxKellermann** [comment]
0e1b28c96dc17c43c366d479ca1ee67f3b47cf7d
