### ISSUE TITLE
Add more or all metadata delimiters

### ISSUE THREAD

**Issue by lasers** [MusicPlayerDaemon/mpc#27]
Hi. I am suggesting `-f, --format` to be updated with more metadata delimiters and/or to print a list of all information... or to have all information exposed in selective `--query` for scripting purposes because there are some things in `mpc status` that are not exposed in `--format`.

Missing:
* `%state%` eg play, pause, stop
* `%volume%` volume percent number, eg 10
* `%repeat%` repeat boolean
* `%random%` repeat boolean
* `%single%` single boolean
* `%consume%` consume boolean
* `%shuffle%` shuffle boolean
* `%progress%` song percent number, eg 10
* `%length%` track length
* etc, etc, etc.

Other things that you might be able to print...
* `%time_total%` (seconds)
* `%time_elapsed%` (seconds)
* `%time_left%` (seconds)
* `%playlist_total%`
* `%playlist_elapsed%`
* `%playlist_left%`
* `%duration%` (seconds)
* `%error%` error message?
* `%bitrate%`
* etc, etc, etc.

If you want a comparsion, you can try...
* moc
    `mocp --format` -- Selective metadata delimiters
    `mocp --info` -- Print (partial?) player status information

* cmus
    `cmus-remote --query`: Print (partial?) player status information

* deadbeef
    `deadbeef --nowplaying "%a - %t"` Print (partial?) status information (deprecated)
    `deadbeef --nowplaying-tf "%artist% - %title%"` uses a subset of [FooBar2K
    title formatting](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#Remapped_metadata_fields)

To explain a bit more about `--query`, this is simply borrowed from what I think is a best example from `nvidia_smi --query-gpu=arg1, arg2, arg3` as it would allow mixing of song information and other information such as `mpc stats` or version. This is basically a generic `--format` that displays literally everything.

eg...
    `mpc --query version, song_artist, stat_artists, stat_albums, stat_songs, stat_play_time, stat_uptime,
    stat_db_updated, stat_db_play_time`

    ... would return: `0.19.0, MaxKellermann, 1, 0, 1, 123456, 123456, ...`

Reason for making this issue. I want to obtain `%status%` and did not see a way to do that with `mpc` (other than ugly parsing the output of `mpc status`) so I write up this possible feature/feature request issue. Thank you.

**Comment by MaxKellermann** [comment]
The `--format` parameter specifies how to format a **song**. Therefore, only a song's metadata is available. And it is only used to format a song, not the whole mpc output.
What you want is a client which outputs arbitrary information obtained by MPD with a custom format. But I don't think this is a good use case for mpc; this is so trivial with a simple Python script:
```
python3 -c 'import mpd; client=mpd.MPDClient(); client.connect("localhost",6600); print(client.status()["volume"])'
```
I admit there is some unnecessary boilerplate code in here, and that Python library should be easier to use; but doing this with Python (or Perl or Ruby or whatever) is so much more powerful and so much more reliable than a shell script calling mpc.
Convince me that your shell script is better than that, and how your shell script will use formatted mpc output in a way better than a sane scripting language will access MPD status information from its client API.

**Comment by lasers** [comment]
First (trivial) issue is that if imported, I may not be able to name it `mpd.py`. :|

The available commands in `mpc` consists of various things... Almost same as `mpc` library. Maybe the other issue is that `mpc` hadn't been updated much and could be improved to support more metadata delimiters... to be something short of an equivalent to `mpc` library?

Second issue.

>MPC, music player command, is a command line tool to interface MPD, Music Player Daemon. It is fast and lightweight like MPD, making it ideal for scripting commands and binding to hotkeys. Completion for the Bash shell is provided.

"Ideal for scripting commands". The main issue is that mpc (which is part of MusicPlayerDaemon here) does not have enough metadata delimiters. Variables like `state` can be useful to have in scripts. Simply put, I already am unable to achieve scripting with what I have in mind with Python and `mpc` due to mpc shortage of metadata delimiters. That's just it.

I do agree with you that using Python library may be better, I think it would be more simplifying to stay away from that and instead parse what users want in their format, then split the output into a dict with a custom delimiter.

>Convince me that your shell script is better than that, and how your shell script will use formatted mpc output in a way better than a sane scripting language will access MPD status information from its client API.

It's not my shell script that will be better than a sane scripting language, but py3status and anything else that have their own formatter. I only need to feed it data and will use its formatter (like your simple one below) to get a nice formatted mpc.
```
The  []  operator  is used to group output such that if no metadata delimiters
are found or matched between '[' and ']', then none of the characters  between
'['  and  ']'  are  output.  '&' and '|' are logical operators for and and or.
'#' is used to escape  characters.   Some  useful  examples  for  format  are:
"%file%"  and  "[[%artist% - ]%title%]|[%file%]".
```
The module internally would really be using `mpc -f '%name%|SEPARATOR|%artist%'`.

I was looking around to see if I can make a cleaner `mpd` module for py3status and to see if I can get more or all metadata delimiters. Having `state` is useful for changing `state` colors.

I just wanted to point out that `mpc` does not offer metadata delimiters for other things, but I do understand that `--format` is for a song only and that people who want something else, eg... current volume in mpd... or current song state... or whatever it is.. will have to use a library.

Another reason why `mpc` might be be better for (shell or Python) scripting... It's easier if we call `mpc stop` and `mpc play` in scripts instead of using a library and is same for other things.

I hope I convince you. Either way, I can use the library since it's the only way to do it.

**Comment by MaxKellermann** [comment]
So you want to make a cleaner mpd module for py3status by periodically spawning mpc and parsing its output, instead of connecting once to MPD with a regular MPD client library? That's a horrifying idea! This is worse in every aspect. Everything is wrong with that idea.
A lot can be improved in py3status's mpd_status.py (e.g. using idle mode instead of querying MPD periodically), but a migration to periodic mpc calls is certainly not an improvement.

**Comment by lasers** [comment]
Not too long ago, `mpd_status` had to make new sockets on every refresh. Now, it's connecting once and keeping that connection alive. `mpd_status` looks messy (in my humble opinion) and I was also curious to see how much I could kill with alternative `mpc --format` only to notice that I ran into lack of delimiters in some other areas...which is why this issue was made in first place.. and had nothing to do with `mpd_status`'s efficiency or lines.

I'll look into `MPDClient.idle()` as that certainly looks more useful over intervals. Thanks for this and I promise I will have a play with it soon enough. Maybe not exactly an improvement, but it did kill so many lines (confirmed 70 lines less... probably more if I didn't touch docs). I doubt I will put out the PR with `mpc` anyway because of too many changes and I have too many opened pull requests. Also unpopular choice.

Other reason why `mpc` was nice. Users can find a list of delimiters in `man mpc` versus telling them to look somewhere. You should see FooBar2K link above. Huge list of delimiters ranging from file sizes, formatting tricks, codecs, etc... which `deadbeef` now uses... Exceeding more than users' needs. All of that kind of information are not available mpd-wise, so maybe this is more than just missing delimiters.

I think it certainly would be a nice enhancement if `mpd` could expose all possible delimiters for `mpc` and the libraries to use. Otherwise, you may close this. And thanks for replying back quickly.

**Comment by ferdnyc** [comment]
Apologies for butting in on what's basically a settled discussion, but I have to say I'm with @MaxKellermann here. Your basic point, @lasers, seems to be that `mpc` is lacking as a tool for querying metadata from MPD, and I don't think anyone would argue with you because that's not what it does. `mpc` is a commandline "remote control" tool for MPD, analogous to the handheld IR remote for a traditional stereo or TV set. That's its **#OneJob**, and it does it well.

In that bit you quoted:
> MPC, music player command, is a command line tool to interface MPD, Music Player Daemon. It is fast and lightweight like MPD, making it ideal for scripting commands and binding to hotkeys. 

"Ideal for scripting commands" was referring to _client-side scripting_ that incorporates `mpc`, to _send commands_ to MPD. Things like "when a Skype call comes in, lower the volume in MPD to 20%", or "Pause the running playlist on logout". `mpc` was never meant to enable robust MPD queries or scripting, merely the interactive (or automated) transmission of control commands and retrieval of some basic state information.

There may well be value in a robust command-line MPD query tool with access to the server's complete metadatabase. But I would argue that if there is, it should be a separate thing, because `mpc` has a different purpose. It is not that tool.

**Comment by MaxKellermann** [comment]
I think we can close this, as mpc is not the right tool for the job, and `--format` is supposed to show only song metadata.
