### ISSUE TITLE
mpc update not removing deleted files

### ISSUE THREAD

**Issue by jameskirsop** [MusicPlayerDaemon/mpc#3]
I've got a library of songs which seems to update when new files are created, but for some reason, mpc update doesn't remove old songs that are no longer in the folder.

As an example, none of the following relative paths are valid in the file system when browsing via cd/lis:
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/01 Re-Hash.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/02 5_4.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/03 Tomorrow Comes Today.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/04 New Genious (Brother).m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/05 Clint Eastwood.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/06 Man Research (Clapper).m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/07 Punk.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/08 Sound Check (Gravity).m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/09 Double Bass.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/10 Rock The House.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/11 19-2000.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/12 Latin Simone.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/13 Starshine.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/14 Slow Country.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/15 M1 A1.m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/16 Clint Eastwood (Ed Case Mix).m4a
iTunes/iTunes Media/Music/Gorillaz/Gorillaz/17 19-2000 (Soulchild Remix).m4a

**Comment by MaxKellermann** [comment]
mpc does not do that, all it does is send commands to MPD. Is this bug report about MPD?
