### ISSUE TITLE
Unable to list playlists with "mpd error"

### ISSUE THREAD

**Issue by alexykot** [MusicPlayerDaemon/mpc#30]
versions:
arch linux
mpd `v0.20.20`
mpc `v0.30`

problem:
running `mpc lsplaylists` throws error `mpd error: Response line too large` and nothing else happens. Have six playlists in one folder. Will be happy to provide more details, not sure what else would be helpful.

**Comment by MaxKellermann** [comment]
When you connect to MPD with telnet and netcat, and type "lsinfo", does MPD respond with anextremely long line? If yes, what is it?

**Comment by alexykot** [comment]
After system upgrade that kicked `mpd` version to `v0.20.21` this no longer reproduces.
