### ISSUE TITLE
Build warning html_static_path entry u'/data/src/mpc/doc/_static' does not exist

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/mpc#33]
$ meson . output
The Meson build system
Version: 0.47.2
Source dir: /data/src/mpc
Build dir: /data/src/mpc/output
Build type: native build
Project name: mpc
Project version: 0.31
Native C compiler: cc (gcc 8.2.0 "cc (Debian 8.2.0-4) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "iconv" : YES
Configuring config.h using configuration
Compiler for C supports arguments -Wall: YES
Compiler for C supports arguments -Wextra: YES
Compiler for C supports arguments -Wno-deprecated-declarations -Wdeprecated-declarations: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wshadow: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Wcast-qual: YES
Compiler for C supports arguments -Wwrite-strings: YES
Compiler for C supports arguments -fvisibility=hidden: YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency libmpdclient found: YES 2.15
Program sphinx-build found: YES (/usr/bin/sphinx-build)
Build targets in project: 3
Found ninja-1.8.2 at /usr/bin/ninja

$ ninja -C output
ninja: Entering directory `output'
[22/22] Generating HTML documentation with a custom command.
WARNING: html_static_path entry u'/data/src/mpc/doc/_static' does not exist

**Comment by MaxKellermann** [comment]
This warning is generated by [Sphinx](http://www.sphinx-doc.org/). It creates the directory, but for an unknown reason warns you that it previously did not exist. I don't know what to do about this, or why this warning even exists. Non-issue.
