### ISSUE TITLE
`MPC_FORMAT` and `mpc ls | mpc add`

### ISSUE THREAD

**Issue by nmeum** [MusicPlayerDaemon/mpc#35]
I would like to change the format used by mpc to also include the `'%position%'` format specifier when performing `mpc playlist` in order to be able to use `mpc play <position>`. This can be achieved by setting the `MPC_FORMAT` environment variable to something along the lines `%position%: [[[%artist% - ]&[%title%]]|[%file%]]`.

Unfortunately, doing so breaks the `mpc ls | mpc add` combination as `mpc ls` will also pickup this format. If `MPC_FORMAT` is unset a different default format seems to be used for `mpc playlist` and `mpc ls`.

I would suggest one of the following solutions:

1. Always ignoring `MPC_FORMAT` in `mpc ls`
2. Allowing the specification of custom format string on a per-subcommand basis (e.g. `MPC_FORMAT_LS`, `MPC_FORMAT_PLAYLIST`, `MPC_FORMAT_CUR`, …)
3. Making `mpc ls` default to format `%file%` when standard out is not a tty.

**Comment by MaxKellermann** [comment]
`mpc ls|mpc add` is not a supported use case. There is never a good reason to do that.

**Comment by MaxKellermann** [comment]
On 2018/10/15 21:22, nmeum <notifications@github.com> wrote:
> Ok I get it. `mpc ls|mpc add` can simply be replaced by `mpc add /` but what about `mpc search artist foo | mpc add`?

mpc findadd
