### ISSUE TITLE
MPC clear not reset track ID

### ISSUE THREAD

**Issue by davama** [MusicPlayerDaemon/mpc#4]
Noticed this when writing some scripts.

So when i clear the mpd playlist and load a new playlist the track IDs get added.

Example:
```
mpc playlist -f "[%id% - %artist%   -   %title%]" | head -5
1 - Amethystium   -   Autumn Interlude
2 - Amethystium   -   Treasure
3 - Andy McKee   -   Ebon Coast
4 - Ayume   -   Hana (Chillout Version)
5 - Blank & Jones   -   Chilled Cream
```
`mpc clear`

`mpc load Chill`

```
mpc playlist -f "[%id% - %artist%   -   %title%]" | head -5
29 - Amethystium   -   Autumn Interlude
30 - Amethystium   -   Treasure
31 - Andy McKee   -   Ebon Coast
32 - Ayume   -   Hana (Chillout Version)
33 - Blank & Jones   -   Chilled Cream

```

If you noticed the TrackID was appended to. My solution on my script is to kill mpd and restart it. Not sure if `mpc clear` is missing anything or this behavior is by design.

Music Player Daemon 0.20.8
mpd version: 0.20.0
OS: 4.10.13-1-ARCH

Thanks
Dave

**Comment by MaxKellermann** [comment]
Since this text does not describe a problem, my random guess is that the submitter misunderstood what "song id" means.
