### ISSUE TITLE
Q: how to use Channels and Messages

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/mpc#43]
Using MPC for bash scripting and it has been good for me, I'd like to know what are Channels and messages (e.g. mpc waitmessage) and how they can help me.

for example, currently I use loop in order to know when playback has been stop using mpc status + grep - it would be great if a single command would do that

**Comment by MaxKellermann** [comment]
This is documented in MPD's protocol documentation: https://www.musicpd.org/doc/html/protocol.html#client-to-client
