### ISSUE TITLE
feature request: tag edit via mpc

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/mpc#47]
something like `mpc tagedit %id {metadata_to_edit} {new value}` e.g. `mpc tagedit 207 genre "Jazz"`

I'd do it for all the classic metadata you can use in "metadata_to_use" of mpd.conf

**Comment by MaxKellermann** [comment]
I'm confused. What exactly is mpc supposed to do with this command?

**Comment by roizcorp** [comment]
to allow me to edit tags (e.g. IDv2) such as artists, title album etc.

**Comment by MaxKellermann** [comment]
mpc is a dumb MPD client. It translates your command line arguments to a MPD command line.
So, technically, which MPD command is mpc supposed to send?

**Comment by roizcorp** [comment]
so what you are saying, If I understand correctly is that my feature request should say "MPD to edit tags"?
I LOVE MPC, it is the universal way to send commands to MPD regardless the device, OS or anything else

**Comment by MaxKellermann** [comment]
I have no idea what your feature request should say. That's why I said I'm confused and why I'm asking questions.
Certainly, MPD is not a tag editor. Just use picard, it's a great software, better than anything MPD could implement in reasonable time.

**Comment by MaxKellermann** [comment]
This feature request doesn't appear to make sense, closing until there are proper answers to my questions.
