### ISSUE TITLE
mpc -f '%position%' search '...' | mpc del does not work, position always 1

### ISSUE THREAD

**Issue by onkobu** [MusicPlayerDaemon/mpc#50]
When I search for artist, genre or title – attribute doesn't matter – format %position% always prints out 1. The search result with default or any other formatting does work, e.g. genre, title, artist. My intention was to delete a list of titles from the queue. The only workaround is with cat -n: mpc playlist | cat -n | grep 'Marlene Dietrich' | awk '{print $1}' | mpc del.

Installation on Gentoo, regular packages: mpd-0.21.16, 0.31. Does it help to upgrade to mpd-0.21.18/ mpc-0.33?

**Comment by MaxKellermann** [comment]
Not a bug. `%position%` is the position in the queue, but since you're searching the database and not the queue, a queue position cannot have a meaningful value.
