### ISSUE TITLE
Add random query type to find and search options

### ISSUE THREAD

**Issue by khaytsus** [MusicPlayerDaemon/mpc#52]
It would be very useful to have the ability ask mpd for a random track matches a query, something like this, although perhaps not the best syntax, just an example.

mpc search '( (genre == "Rock") AND (random) )'

Which would return one random song that is of the Rock genre, or of course could be combined with any other queries that search/find can use.

**Comment by MaxKellermann** [comment]
Try this: `mpc search genre Rock|shuf -n1`

**Comment by khaytsus** [comment]
Well yes, but that's fairly inefficient to get thousands of songs every invocation instead of filtering on the server side, which it already can do random selections to my understanding.

**Comment by MaxKellermann** [comment]
No, it can't.
