### ISSUE TITLE
Provide return code for mpc

### ISSUE THREAD

**Issue by khaytsus** [MusicPlayerDaemon/mpc#55]
mpc currently does not appear to provide any return code, so scripts have no idea if the command succeeded or not.  Primarily in the case of mpd not running, but other errors returning a non-0 value would be nice too.

Currently working around this by looking for version and assuming an empty string means mpd is not available, but that's a bit kludgy.  If mpc just returned non-zero it would be a better way to determine if mpd is available or not.

**Comment by MaxKellermann** [comment]
What is a "return code"?
Demonstrate the problem.

**Comment by khaytsus** [comment]
Sigh.  I'm an idiot, I had a typo and was not testing $?, I am getting what I expect now, sorry.
