### ISSUE TITLE
new metadata delimiter for mpc --format

### ISSUE THREAD

**Issue by DavidHenryThoreau** [MusicPlayerDaemon/mpc#57]
Hi,

After reading man mpc in section metadata delimiter it'd be nice to add new values :
- current elapsed time in playing song (for the moment only %time% is available)
- how many tracks there is in the album's song in order to display ( mpc current -f "%track% %tracks%")

**Comment by MaxKellermann** [comment]
Both of these are not properties of the song to be formatted, thus the part of the code doing this doesn't have the required information.
This could be changed by adding code complexity, but I doubt the general usefulness of the feature.
What is your use case?
(If you say you want to use mpc in shell scripts, then: don't. At this stage, you're better off writing a Python script or a similar scripting language with a good MPD client libary.)

**Comment by lienjul** [comment]
I need these two values in order to diplay them in [i3blocks](https://github.com/vivien/i3blocks)
Can you give me good MPD client libary links ?

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/libs/

Though i3blocks doesn't look like a good solution - it would be best to have a persistent client process with a persistent MPD connection which doesn't fork/execute a new process every second and doesn't create new connections each time.
