### ISSUE TITLE
mpc status: inconsistent volume output

### ISSUE THREAD

**Issue by acreter** [MusicPlayerDaemon/mpc#59]
At 100% volume mpc prints  `volume:100%`. At <=99% volume we get `volume: xx%` (with a space).
This makes it unnecessarily hard to extract the volume with programs like awk.
Is there any reason why the volume is printed with
https://github.com/MusicPlayerDaemon/mpc/blob/4cb12feafc4dd9d25847883e27b5d9326729e530/src/status.c#L92 instead of
`printf("volume: %3i%c  ", mpd_status_get_volume(status), '%');`

This also applies to the `mpc volume` command:
https://github.com/MusicPlayerDaemon/mpc/blob/da8df7e82f5131924e6ce3ef1effeec5877069c3/src/command.c#L881

**Comment by MaxKellermann** [comment]
I don't understand the point. So some programs use the space as a separator, but what mpc actually implements is the colon.
I think we should rather have colon plus a space, and omit the integer format width. That one is pointless, and has always been.
Note that mpc isn't the best way to programmatically obtain information from MPD, and thus this will never be its priority: if you need to have the volume value in a script, just use one of the many MPD client libraries. Even if it's just netcat.

**Comment by warichnict** [comment]
where exactly is the problem in writing something that will get you what you need @acreter ? 

some bash code:
````
mpc | grep volume |cut -f 2 -d ' ' | cut -f 1 -d '%'
````
just took me some seconds

**Comment by Najoj** [comment]
I would rather see the prepended "volume" string removed. That is, `printf("%i%c\n", ...);`.
