### ISSUE TITLE
mpc displays the track length of some opus files to be 0:00 when it is, in fact, not 0:00

### ISSUE THREAD

**Issue by kartikynwa** [MusicPlayerDaemon/mpc#61]
Example output:

```
# mpc
Hum - The Very Old Man
[paused]  #1/1   2:13/0:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: on
```

I have uploaded the opus file here in case you want to test: https://transfer.sh/xLz9c/opus_file.zip

Let me know if sharing the song is problematic because of copyright issues or better yet just delete the issue yourself. :)

**Comment by MaxKellermann** [comment]
mpc just prints what it receives from MPD. If you believe the information given by MPD is wrong, report it over there.
