### ISSUE TITLE
mpc next stuck

### ISSUE THREAD

**Issue by EdgarLGB** [MusicPlayerDaemon/mpc#62]
Hello,

I have a MPD installed on a Raspberry Pi and a MPC on my Mac. I managed to play a track by using the cmd `$mpc play`. But when I executed `$mpc next`, I got a `MPD error: Timeout`. Could you give me a clue on this?

Thanks

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by MaxKellermann** [comment]
No reply.
