### ISSUE TITLE
[Feature Request] JSON Output

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/mpc#65]
I use mpc to communicate with MPD, I am not a developer, I parse the variety of bash outputs and use them as I need.

The option to output mpc commands of playlist, status or anything really will access data faster, currently I assemble the json by myself via the format option but it should really become the standard now

Thanks for the awesome work so far

**Comment by MaxKellermann** [comment]
I don't think mpc is the right tool for the job. If you want to programmatically handle structured information received from MPD, you should not use mpc with shell scripts; instead, you should use a better scripting language than shell and use a MPD client library. For example, a few lines of Python are much more powerful and more reliable than any shell script can ever be.
Adding JSON support to mpc would add a huge amount of overhead; it would probably double or triple the size of the program. And in the end, it's an inferior solution to your problem.

**Comment by SX-9** [comment]
Man i wish this was a fuature
