### ISSUE TITLE
Volume stays at "n/a"

### ISSUE THREAD

**Issue by DaMusikant** [MusicPlayerDaemon/mpc#66]
Hi there,
as I tried to getting mpc running on my Raspberry 2 the volume stays at "n/a" and don't plays any music.

`pi@raspberrypi:~ $ mpc volume 100
volume: n/a   repeat: off   random: off   single: off   consume: off
` 

As an output I declared the ALSA device

`pi@raspberrypi:~ $ mpc outputs
Output 1 (My ALSA Device) is enabled
`

I don't know the background of the player, so where the volume is comming from.
The audio files are shown right and the test audio is working, as an output of ALSA I declared the headphone jack.

One thing that i mentioned is that if am asking him about the current song I don't get any information.

Can someone help me? Google doesn't seem to have any helpfull information... Thank you :)

**Comment by MaxKellermann** [comment]
mpc displays whatever information it gets from MPD. What you described is not a mpc problem, but maybe a MPD misconfiguration. Since you havn't posted any information, I can't help, but anyway this is the wrong place to discuss MPD problems.
