### ISSUE TITLE
systemd failure on fedora 26 with fusion rpm - fresh install

### ISSUE THREAD

**Issue by ieei4n7u1710n** [MusicPlayerDaemon/mpc#8]
Oct  6 15:07:59 ab audit: USER_AUTH pid=5506 uid=1000 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=pam_unix acct="9gkm4" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Oct  6 15:07:59 ab audit: USER_ACCT pid=5506 uid=1000 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:accounting grantors=pam_unix,pam_localuser acct="9gkm4" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Oct  6 15:07:59 ab audit: USER_CMD pid=5506 uid=1000 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home/9gkm4" cmd=73797374656D63746C207374617274206D7064 terminal=pts/0 res=success'
Oct  6 15:07:59 ab audit: CRED_REFR pid=5506 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Oct  6 15:07:59 ab audit: USER_START pid=5506 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Oct  6 15:07:59 ab systemd: Starting Music Player Daemon...
Oct  6 15:07:59 ab audit: SELINUX_ERR op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:init_t:s0 newcontext=system_u:system_r:mpd_t:s0
Oct  6 15:07:59 ab audit: AVC avc:  denied  { append } for  pid=5512 comm="mpd" name="mpd.log" dev="dm-1" ino=1315238 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:mpd_log_t:s0 tclass=file permissive=0
Oct  6 15:07:59 ab mpd: exception: failed to open log file "/var/log/mpd/mpd.log" (config line 37): Permission denied
Oct  6 15:07:59 ab systemd: mpd.service: Main process exited, code=exited, status=1/FAILURE
Oct  6 15:07:59 ab systemd: Failed to start Music Player Daemon.
Oct  6 15:07:59 ab audit: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=mpd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Oct  6 15:07:59 ab systemd: mpd.service: Unit entered failed state.
Oct  6 15:07:59 ab systemd: mpd.service: Failed with result 'exit-code'.
Oct  6 15:07:59 ab audit: USER_END pid=5506 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Oct  6 15:07:59 ab audit: CRED_DISP pid=5506 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'

**Comment by MaxKellermann** [comment]
Your paste clearly shows that you misconfigured SELinux.

And besides that, your bug report is bad because you don't even mention the MPD version.

**Comment by ieei4n7u1710n** [comment]
My apologies. This seems to be standard in Fedora Workstation as I did not set it up. Would be nice to know for future users however I guess this is for the repository? 

Thanks for pointing out the lack in bug report. You unlocked my bug-reading ability as well with the first line!
