### ISSUE TITLE
mpc version reports incorrect mpd version

### ISSUE THREAD

**Issue by macmpi** [MusicPlayerDaemon/mpc#88]
running `mpd` server 0.23.7 and `mpc` 0.34: `mpc` reports `mpd` as 0.23.5
```
$ mpd --version
Music Player Daemon 0.23.7 (v20220328-3728-g23ddff1f98)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>

$ mpc version
mpd version: 0.23.5
```

**Comment by MaxKellermann** [comment]
This is the protocol version, not the MPD version.

**Comment by macmpi** [comment]
Ok, thanks.
Maybe doc needs to be clarified then
https://www.musicpd.org/doc/mpc/html/

> version - Reports the version of MPD.
