### ISSUE TITLE
add elapsed time format

### ISSUE THREAD

**Issue by glensc** [MusicPlayerDaemon/mpc#9]
status command is able to display current elapsed time:

```
[playing] #1/8   0:28/4:32 (10%)
```

but not possible with `-f`.

i want to script this in my [web script](https://github.com/glensc/mpd-lyrics/blob/6258d546465000071a503abbfc89a7ed9116ea3a/lyrics.cgi) to refresh page when the song playing has ended. i.e setup "Refresh: $seconds" http header.

**Comment by MaxKellermann** [comment]
That's because the elapsed time is an attribute of the player, not of the song. And `-f` is used to format the song.

But your script isn't so good because it opens three connections to MPD. And it has Python. And that Python snippet works only if `mpc` runs on the same machine as MPD. And the music directory is hard-coded instead of querying it from MPD.

Consider this Python code:

    #!/usr/bin/env python3
    import mpd, os
    client = mpd.MPDClient(use_unicode=True)
    client.connect("/run/mpd/socket", 6600)
    status = client.status()
    song = client.currentsong()
    
    print("%s - %s [%s]" % (song['artist'], song['title'], status['elapsed']))
    
    try:
        from mutagen.id3 import ID3
        music_directory = client.config()
        song_path = os.path.join(music_directory, song['file'])
        print(ID3(song_path).getall("USLT")[0])
    except:
        print("Lyrics not embedded into file")

This is simpler, faster, more robust and uses only one single MPD connection.

**Comment by glensc** [comment]
thanks for the snippet.

it was quickly thrown together, had plans to rewrite in python at some point.

and the script needs to run on mpd host (or have music directory mounted) because id3 tag read needs access to the file. i wish mpd could support querying lyric tags over mpd protocol. but i haven't got around to submit related feature requests to projects (mpd, mpc, gmpc). maybe somebody already has requested.

**Comment by glensc** [comment]
hmm, which mpd python library were you using?

[python-mpd](https://pypi.python.org/pypi/python-mpd/) from debian having 0.3.0 version does not have `.config` attribute

```
Traceback (most recent call last):
  File "./lyrics.cgi", line 33, in <module>
    music_directory = client.config()
  File "/usr/lib/python2.7/dist-packages/mpd.py", line 166, in __getattr__
    (self.__class__.__name__, attr))
AttributeError: 'MPDClient' object has no attribute 'config'

```
