### ISSUE TITLE
Start an audio file in a specific time

### ISSUE THREAD

**Issue by carlos-f-h-duarte** [MusicPlayerDaemon/mpc#92]
Hi!
Is it possible with a mpc start an audio file in a specific time ex. : 10:05 (other then with crontab) with a following condition:
The mpc is playing a song (playlist), at 10:05 start an audio message and pause the song. After the message, unpause the current song.
Thank you

**Comment by MaxKellermann** [comment]
No. mpc is a simple command-line tool to submit commands to MPD. But you can combine it with `at` to schedule certain MPD comands at certain times.
