### ISSUE TITLE
 mpc-completion doesn't work properly if a user defines `$MPC_FORMAT`

### ISSUE THREAD

**Issue by unera** [MusicPlayerDaemon/mpc#94]
> manpage:
>        MPC_FORMAT
>              Configure the format used to display songs.  See option --format.

for example, I want to see the filename when I do `mpc status` (or `mpc`) in a console, so I define in my zshrc the following line:

```
export MPC_FORMAT='%artist% - %title% ( "%file%" )'
```

Since then, I have found that completions for `mpc add` etc are thoroughly broken.

**Comment by MaxKellermann** [comment]
The completion code has been written by many drive-by contributors, but there is no maintainer. If you want this fixed, submit a PR.

**Comment by MaxKellermann** [comment]
Half a year later, nobody was interested in fixing this bug. If this issue continues to exist, the completion scripts will be deleted.

**Comment by izmyname** [comment]
Alternative solution might be removing MPC_FORMAT variable and implementing a config file, where default format output for commands like 'mpc playlist' could be specified.

**Comment by izmyname** [comment]
UPD: There's a hacky solution - add alias mpc ="mpc -f %position%... etc" in .zshrc. It applies formatting to all mpc commands but does not break completions.

**Comment by MaxKellermann** [comment]
That's not a hacky solution - it's a solution. If you expect mpc to print a certain format, specify it explicitly instead of assuming that mpc uses its defaults. Do you want to submit a PR?

**Comment by MaxKellermann** [comment]
Oh, that you mean. I thought you had added `-f` to the bash completion script. Because that would be the solution.

**Comment by izmyname** [comment]
Unfortunately, the problem still persists for me with ZSH shell.  Falling back to using alias.

**Comment by izmyname** [comment]
For fellow zsh users, who faced the same problem and found this issue - here's a workaround.

_~/.zshrc_
```

 autoload -Uz  bashcompinit
 
bashcompinit

source /usr/share/bash-completion/completions/mpc

export MPC_FORMAT=%whatever%
```
Now, you can use working bash completion for MPC. It also fixes `mpc insert` command.
